/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Guid = string;
/**
 * Deprecated: auth_bypass_ids should be sent as a separate field
 */
export type GuidList = Guid[];
/**
 * A list of organisation content ids permitted access to this item
 */
export type GuidList1 = Guid[];
/**
 * A short identifier we send to Google Analytics for multi-valued fields. This means we avoid the truncated values we would get if we sent the path or slug of eg organisations.
 */
export type AnalyticsIdentifier = string | null;
/**
 * A list of ids that will allow access to this item for non-authenticated users
 */
export type GuidList2 = Guid[];
/**
 * A path only. Query string and/or fragment are not allowed.
 */
export type AbsolutePath = string;
export type DescriptionOptional = Description | null;
export type Description = string;
/**
 * The main content provided as HTML rendered from govspeak
 */
export type Body = string;
/**
 * A list of URLs and titles for a brexit no deal notice.
 */
export type BrexitNoDealNotice = {
  href: string;
  title: string;
}[];
export type ChangeHistory = {
  /**
   * A summary of the change
   */
  note: string;
  public_timestamp: string;
}[];
/**
 * The content ids of the organisations that should be displayed first in the list of organisations related to the item, these content ids must be present in the item organisation links hash.
 */
export type EmphasisedOrganisations = Guid[];
/**
 * DEPRECATED. The date the content was first published. Used in details. Deprecated in favour of top level `first_published_at`.
 */
export type FirstPublicAt = string;
/**
 * The date the content was first published.  Automatically determined by the publishing-api, unless overridden by the publishing application.
 */
export type FirstPublishedAt = string;
/**
 * A largely deprecated tag currently only used to power email alerts.
 */
export type GuidList3 = Guid[];
export type Locale =
  | "ar"
  | "az"
  | "be"
  | "bg"
  | "bn"
  | "cs"
  | "cy"
  | "da"
  | "de"
  | "dr"
  | "el"
  | "en"
  | "es"
  | "es-419"
  | "et"
  | "fa"
  | "fi"
  | "fr"
  | "gd"
  | "gu"
  | "he"
  | "hi"
  | "hr"
  | "hu"
  | "hy"
  | "id"
  | "is"
  | "it"
  | "ja"
  | "ka"
  | "kk"
  | "ko"
  | "lt"
  | "lv"
  | "ms"
  | "mt"
  | "ne"
  | "nl"
  | "no"
  | "pa"
  | "pa-pk"
  | "pl"
  | "ps"
  | "pt"
  | "ro"
  | "ru"
  | "si"
  | "sk"
  | "sl"
  | "so"
  | "sq"
  | "sr"
  | "sv"
  | "sw"
  | "ta"
  | "th"
  | "tk"
  | "tr"
  | "uk"
  | "ur"
  | "uz"
  | "vi"
  | "yi"
  | "zh"
  | "zh-hk"
  | "zh-tw";
/**
 * When the content was last significantly changed (a major update). Shown to users.  Automatically determined by the publishing-api, unless overridden by the publishing application.
 */
export type PublicUpdatedAt = string;
/**
 * The application that published this item.
 */
export type PublishingAppName =
  | "account-api"
  | "calculators"
  | "calendars"
  | "collections-publisher"
  | "contacts"
  | "content-publisher"
  | "content-tagger"
  | "email-alert-frontend"
  | "external-link-tracker"
  | "feedback"
  | "frontend"
  | "government-frontend"
  | "hmrc-manuals-api"
  | "info-frontend"
  | "licencefinder"
  | "local-links-manager"
  | "manuals-publisher"
  | "maslow"
  | "performanceplatform-big-screen-view"
  | "publisher"
  | "rummager"
  | "search-admin"
  | "search-api"
  | "service-manual-publisher"
  | "share-sale-publisher"
  | "short-url-manager"
  | "smartanswers"
  | "special-route-publisher"
  | "specialist-publisher"
  | "static"
  | "tariff"
  | "travel-advice-publisher"
  | "whitehall";
/**
 * The application that renders this item.
 */
export type RenderingApp =
  | "account-api"
  | "calculators"
  | "calendars"
  | "collections"
  | "content-store"
  | "email-alert-frontend"
  | "email-campaign-frontend"
  | "feedback"
  | "finder-frontend"
  | "frontend"
  | "government-frontend"
  | "info-frontend"
  | "licencefinder"
  | "performanceplatform-big-screen-view"
  | "rummager"
  | "search-api"
  | "service-manual-frontend"
  | "smartanswers"
  | "spotlight"
  | "static"
  | "tariff"
  | "whitehall-admin"
  | "whitehall-frontend";
/**
 * @minItems 1
 */
export type Routes = [Route, ...Route[]];
export type Title = string;
export type UpdateType = "major" | "minor" | "republish";

export interface CaseStudySchema {
  access_limited?: AccessLimited;
  analytics_identifier?: AnalyticsIdentifier;
  auth_bypass_ids?: GuidList2;
  base_path: AbsolutePath;
  bulk_publishing?: boolean;
  change_note?: null | string;
  description?: DescriptionOptional;
  details: Details;
  document_type: "case_study";
  first_published_at?: FirstPublishedAt;
  /**
   * Last time when the content received a major or minor update.
   */
  last_edited_at?: string;
  links?: {
    policy_areas?: GuidList3;
  };
  locale?: Locale;
  need_ids?: string[];
  /**
   * The service design phase of this content item - https://www.gov.uk/service-manual/phases
   */
  phase?: "alpha" | "beta" | "live";
  previous_version?: string;
  public_updated_at?: PublicUpdatedAt;
  publishing_app: PublishingAppName;
  redirects?: unknown[];
  rendering_app: RenderingApp;
  routes: Routes;
  schema_name: "case_study";
  title: Title;
  update_type?: UpdateType;
}
export interface AccessLimited {
  auth_bypass_ids?: GuidList;
  organisations?: GuidList1;
  users?: string[];
}
export interface Details {
  archive_notice?: {
    archived_at?: {
      [k: string]: unknown;
    };
    explanation?: string;
  };
  body: Body;
  brexit_no_deal_notice?: BrexitNoDealNotice;
  change_history?: ChangeHistory;
  emphasised_organisations?: EmphasisedOrganisations;
  first_public_at?: FirstPublicAt;
  format_display_type?: "case_study";
  image?: Image;
  tags?: Tags;
}
export interface Image {
  alt_text?: string;
  caption?: string | null;
  credit?: string | null;
  /**
   * URL to a high resolution version of the image, for use by third parties such as Twitter, Facebook or Slack. Used by the machine readable metadata component. Don't use this on user-facing web pages, as it might be very large.
   */
  high_resolution_url?: string;
  /**
   * URL to the image. The image should be in a suitable resolution for display on the page.
   */
  url: string;
}
/**
 * Field used by email-alert-api to trigger email alerts for subscriptions to topics (gov.uk/topic) and policies (gov.uk/policies).
 */
export interface Tags {
  additional_topics?: string[];
  browse_pages?: string[];
  policies?: string[];
  primary_topic?: string[];
  topics?: string[];
}
export interface Route {
  path: string;
  type: "prefix" | "exact";
}
