/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Guid = string;
/**
 * Deprecated: auth_bypass_ids should be sent as a separate field
 */
export type GuidList = Guid[];
/**
 * A list of organisation content ids permitted access to this item
 */
export type GuidList1 = Guid[];
/**
 * A short identifier we send to Google Analytics for multi-valued fields. This means we avoid the truncated values we would get if we sent the path or slug of eg organisations.
 */
export type AnalyticsIdentifier = string | null;
/**
 * A list of ids that will allow access to this item for non-authenticated users
 */
export type GuidList2 = Guid[];
/**
 * A path only. Query string and/or fragment are not allowed.
 */
export type AbsolutePath = string;
export type DescriptionOptional = Description | null;
export type Description = string;
/**
 * The content ids of the organisations that should be displayed first in the list of organisations related to the item, these content ids must be present in the item organisation links hash.
 */
export type EmphasisedOrganisations = Guid[];
/**
 * The date the content was first published.  Automatically determined by the publishing-api, unless overridden by the publishing application.
 */
export type FirstPublishedAt = string;
/**
 * A largely deprecated tag currently only used to power email alerts.
 */
export type GuidList3 = Guid[];
export type Locale =
  | "ar"
  | "az"
  | "be"
  | "bg"
  | "bn"
  | "cs"
  | "cy"
  | "da"
  | "de"
  | "dr"
  | "el"
  | "en"
  | "es"
  | "es-419"
  | "et"
  | "fa"
  | "fi"
  | "fr"
  | "gd"
  | "gu"
  | "he"
  | "hi"
  | "hr"
  | "hu"
  | "hy"
  | "id"
  | "is"
  | "it"
  | "ja"
  | "ka"
  | "kk"
  | "ko"
  | "lt"
  | "lv"
  | "ms"
  | "mt"
  | "ne"
  | "nl"
  | "no"
  | "pa"
  | "pa-pk"
  | "pl"
  | "ps"
  | "pt"
  | "ro"
  | "ru"
  | "si"
  | "sk"
  | "sl"
  | "so"
  | "sq"
  | "sr"
  | "sv"
  | "sw"
  | "ta"
  | "th"
  | "tk"
  | "tr"
  | "uk"
  | "ur"
  | "uz"
  | "vi"
  | "yi"
  | "zh"
  | "zh-hk"
  | "zh-tw";
/**
 * When the content was last significantly changed (a major update). Shown to users.  Automatically determined by the publishing-api, unless overridden by the publishing application.
 */
export type PublicUpdatedAt = string;
/**
 * The application that published this item.
 */
export type PublishingAppName =
  | "account-api"
  | "calculators"
  | "calendars"
  | "collections-publisher"
  | "contacts"
  | "content-publisher"
  | "content-tagger"
  | "email-alert-frontend"
  | "external-link-tracker"
  | "feedback"
  | "frontend"
  | "government-frontend"
  | "hmrc-manuals-api"
  | "info-frontend"
  | "licencefinder"
  | "local-links-manager"
  | "manuals-publisher"
  | "maslow"
  | "performanceplatform-big-screen-view"
  | "publisher"
  | "rummager"
  | "search-admin"
  | "search-api"
  | "service-manual-publisher"
  | "share-sale-publisher"
  | "short-url-manager"
  | "smartanswers"
  | "special-route-publisher"
  | "specialist-publisher"
  | "static"
  | "tariff"
  | "travel-advice-publisher"
  | "whitehall";
/**
 * The application that renders this item.
 */
export type RenderingApp =
  | "account-api"
  | "calculators"
  | "calendars"
  | "collections"
  | "content-store"
  | "email-alert-frontend"
  | "email-campaign-frontend"
  | "feedback"
  | "finder-frontend"
  | "frontend"
  | "government-frontend"
  | "info-frontend"
  | "licencefinder"
  | "performanceplatform-big-screen-view"
  | "rummager"
  | "search-api"
  | "service-manual-frontend"
  | "smartanswers"
  | "spotlight"
  | "static"
  | "tariff"
  | "whitehall-admin"
  | "whitehall-frontend";
/**
 * @minItems 1
 */
export type Routes = [Route, ...Route[]];
export type Title = string;
export type UpdateType = "major" | "minor" | "republish";

export interface TopicalEventSchema {
  access_limited?: AccessLimited;
  analytics_identifier?: AnalyticsIdentifier;
  auth_bypass_ids?: GuidList2;
  base_path: AbsolutePath;
  bulk_publishing?: boolean;
  change_note?: null | string;
  description?: DescriptionOptional;
  details: Details;
  document_type:
    | "aaib_report"
    | "about"
    | "about_our_services"
    | "accessible_documents_policy"
    | "access_and_opening"
    | "ambassador_role"
    | "animal_disease_case"
    | "answer"
    | "asylum_support_decision"
    | "authored_article"
    | "board_member_role"
    | "business_finance_support_scheme"
    | "calculator"
    | "calendar"
    | "case_study"
    | "chief_professional_officer_role"
    | "chief_scientific_officer_role"
    | "chief_scientific_advisor_role"
    | "closed_consultation"
    | "cma_case"
    | "coming_soon"
    | "complaints_procedure"
    | "completed_transaction"
    | "consultation"
    | "consultation_outcome"
    | "contact"
    | "coronavirus_landing_page"
    | "corporate_report"
    | "correspondence"
    | "countryside_stewardship_grant"
    | "decision"
    | "deputy_head_of_mission_role"
    | "detailed_guidance"
    | "detailed_guide"
    | "dfid_research_output"
    | "document_collection"
    | "drcf_digital_markets_research"
    | "drug_safety_update"
    | "email_alert_signup"
    | "employment_appeal_tribunal_decision"
    | "employment_tribunal_decision"
    | "equality_and_diversity"
    | "esi_fund"
    | "export_health_certificate"
    | "external_content"
    | "facet"
    | "fatality_notice"
    | "field_of_operation"
    | "finder"
    | "finder_email_signup"
    | "flood_and_coastal_erosion_risk_management_research_report"
    | "foi_release"
    | "form"
    | "get_involved"
    | "gone"
    | "government"
    | "government_response"
    | "governor_role"
    | "guidance"
    | "guide"
    | "help_page"
    | "high_commissioner_role"
    | "history"
    | "hmrc_manual"
    | "hmrc_manual_section"
    | "homepage"
    | "html_publication"
    | "impact_assessment"
    | "imported"
    | "independent_report"
    | "international_development_fund"
    | "international_treaty"
    | "knowledge_alpha"
    | "licence"
    | "license_finder"
    | "local_transaction"
    | "maib_report"
    | "mainstream_browse_page"
    | "manual"
    | "manual_section"
    | "map"
    | "marine_notice"
    | "media_enquiries"
    | "medical_safety_alert"
    | "membership"
    | "military_role"
    | "ministerial_role"
    | "ministers_index"
    | "modern_slavery_statement"
    | "national"
    | "national_statistics"
    | "national_statistics_announcement"
    | "need"
    | "news_article"
    | "news_story"
    | "notice"
    | "official"
    | "official_statistics"
    | "official_statistics_announcement"
    | "oim_project"
    | "open_consultation"
    | "oral_statement"
    | "organisation"
    | "our_energy_use"
    | "our_governance"
    | "person"
    | "personal_information_charter"
    | "petitions_and_campaigns"
    | "place"
    | "placeholder"
    | "placeholder_ministerial_role"
    | "placeholder_organisation"
    | "placeholder_person"
    | "placeholder_policy_area"
    | "placeholder_worldwide_organisation"
    | "policy_area"
    | "policy_paper"
    | "press_release"
    | "procurement"
    | "product_safety_alert_report_recall"
    | "promotional"
    | "protected_food_drink_name"
    | "publication_scheme"
    | "raib_report"
    | "recruitment"
    | "redirect"
    | "regulation"
    | "research"
    | "research_for_development_output"
    | "residential_property_tribunal_decision"
    | "role_appointment"
    | "search"
    | "service_manual_guide"
    | "service_manual_homepage"
    | "service_manual_service_standard"
    | "service_manual_service_toolkit"
    | "service_manual_topic"
    | "service_sign_in"
    | "service_standard_report"
    | "services_and_information"
    | "simple_smart_answer"
    | "smart_answer"
    | "social_media_use"
    | "special_representative_role"
    | "special_route"
    | "speech"
    | "staff_update"
    | "standard"
    | "statistical_data_set"
    | "statistics"
    | "statistics_announcement"
    | "statutory_guidance"
    | "statutory_instrument"
    | "step_by_step_nav"
    | "take_part"
    | "tax_tribunal_decision"
    | "taxon"
    | "terms_of_reference"
    | "topic"
    | "topical_event"
    | "topical_event_about_page"
    | "traffic_commissioner_regulatory_decision"
    | "traffic_commissioner_role"
    | "transaction"
    | "transparency"
    | "travel_advice"
    | "travel_advice_index"
    | "unpublishing"
    | "uk_market_conformity_assessment_body"
    | "utaac_decision"
    | "vanish"
    | "welsh_language_scheme"
    | "working_group"
    | "world_location"
    | "world_location_news"
    | "world_news_story"
    | "worldwide_office_staff_role"
    | "worldwide_organisation"
    | "written_statement";
  first_published_at?: FirstPublishedAt;
  /**
   * Last time when the content received a major or minor update.
   */
  last_edited_at?: string;
  links?: {
    policy_areas?: GuidList3;
  };
  locale?: Locale;
  need_ids?: string[];
  /**
   * The service design phase of this content item - https://www.gov.uk/service-manual/phases
   */
  phase?: "alpha" | "beta" | "live";
  previous_version?: string;
  public_updated_at?: PublicUpdatedAt;
  publishing_app: PublishingAppName;
  redirects?: unknown[];
  rendering_app: RenderingApp;
  routes: Routes;
  schema_name: "topical_event";
  title: Title;
  update_type?: UpdateType;
}
export interface AccessLimited {
  auth_bypass_ids?: GuidList;
  organisations?: GuidList1;
  users?: string[];
}
export interface Details {
  about_page_link_text?: string;
  /**
   * The main content provided as HTML rendered from govspeak
   */
  body?: string;
  emphasised_organisations?: EmphasisedOrganisations;
  end_date?: string;
  image?: {
    alt_text?: string;
    url?: string;
    [k: string]: unknown;
  };
  /**
   * A set of featured documents to display for the Topical Event.
   */
  ordered_featured_documents?: {
    href: string;
    image: Image;
    summary: string;
    title: string;
  }[];
  /**
   * A set of links to social media profiles for the topical event.
   */
  social_media_links?: {
    href: string;
    service_type:
      | "blog"
      | "email"
      | "facebook"
      | "flickr"
      | "foursquare"
      | "google-plus"
      | "instagram"
      | "linkedin"
      | "other"
      | "pinterest"
      | "twitter"
      | "youtube";
    title: string;
  }[];
  start_date?: string;
}
export interface Image {
  alt_text?: string;
  caption?: string | null;
  credit?: string | null;
  /**
   * URL to a high resolution version of the image, for use by third parties such as Twitter, Facebook or Slack. Used by the machine readable metadata component. Don't use this on user-facing web pages, as it might be very large.
   */
  high_resolution_url?: string;
  /**
   * URL to the image. The image should be in a suitable resolution for display on the page.
   */
  url: string;
}
export interface Route {
  path: string;
  type: "prefix" | "exact";
}
